//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coding_Tech.Models.CTDbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCustomer
    {
        public int id { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public int City { get; set; }
        public Nullable<int> County { get; set; }
        public Nullable<decimal> Mobile { get; set; }
        public Nullable<decimal> Landline { get; set; }
        public string Email { get; set; }
        public Nullable<decimal> CNIC { get; set; }
    
        public virtual tblCity tblCity { get; set; }
        public virtual tblCountry tblCountry { get; set; }
    }
}
