//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coding_Tech.Models.CTDbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblInterest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblInterest()
        {
            this.tblUsers = new HashSet<tblUser>();
        }
    
        public int id { get; set; }
        public Nullable<bool> C_ { get; set; }
        public Nullable<bool> PHP { get; set; }
        public Nullable<bool> Python { get; set; }
        public Nullable<bool> Ruby { get; set; }
        public Nullable<bool> VB { get; set; }
        public Nullable<bool> React { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblUser> tblUsers { get; set; }
    }
}
