//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coding_Tech.Models.CTDbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblShop
    {
        public int id { get; set; }
        public Nullable<int> Floor { get; set; }
        public string Description { get; set; }
    
        public virtual tblFloor tblFloor { get; set; }
    }
}
