//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coding_Tech.Models.CTDbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUser
    {
        public int Uid { get; set; }
        public string FullName { get; set; }
        public string Username { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string Gender { get; set; }
        public Nullable<int> Interests { get; set; }
        public string Password { get; set; }
        public string ImagePath { get; set; }
    
        public virtual tblInterest tblInterest { get; set; }
    }
}
